name: Max Binder
favicon: null
layout_spectrum: 0.04138
typography_spectrum: 0.48274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#593f2e'
    - '#aea9a5'
    - '#777b87'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
